### ISSUE TITLE
[bug] 500 error when trying to edit bio

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#229] opened 2022-05-24 13:57 UTC
### Page

Your profile page

#### Video
https://user-images.githubusercontent.com/43812987/170052667-66d672ac-a9bb-464c-bab3-92c8a175d04d.mp4
## Console output
![image](https://user-images.githubusercontent.com/43812987/170052951-c293dee5-1339-48c0-80bf-b6a67b686695.png)

#### Notify on issue updates

- [X] Yes

### Discord username

SCDerox#4645

**Comment by audn** [comment] 2022-05-24 14:10
Duplicate of #227 

It doesn't look like a duplicate, but these two errors are because of the latest icon change that I pinged in the #updates channel earlier today.

I will proceed to close the issue.

_Thank you for contributing during beta!_

**Closed by audn** 2022-05-24 14:10 UTC
Labels: bug
