### ISSUE TITLE
[Bug] Apps page crashes

### ISSUE THREAD

**Issue by XanderD99** [discordlist-gg/beta-issues#40] opened 2021-08-30 16:31 UTC
## Description
When visiting https://beta.discordlist.gg/user/apps before you have any it crashes the page.
Initially it loads the page but as soon as `e.bots` value is needed it crashes
![image](https://user-images.githubusercontent.com/36887752/131372420-7f24ef86-132f-43e6-88bb-a66f5535e430.png)

## Possible Solution
I think an if statement to prevent the e.bots value being undefined

## Steps to Reproduce (for bugs)
1. log in with user without apps
2. go to https://beta.discordlist.gg/user/apps 
3. ???
4. crash

**Comment by audn** [comment] 2021-08-31 07:08
Duplicate of https://github.com/discordlist-gg/beta-issues/issues/20

**Closed by audn** 2021-08-31 07:08 UTC
Labels: bug
