### ISSUE TITLE
AUDN!!!!

### ISSUE THREAD

**Issue by ErginDapaj** [discordlist-gg/beta-issues#206] opened 2022-05-20 14:16 UTC
### Page

Application Page

### Description

![Screenshot_20220520-161504_Chrome](https://user-images.githubusercontent.com/39377884/169547148-04a2c26e-29a2-4d00-8042-ad7b45e613de.jpg)

**Comment by audn** [comment] 2022-05-20 14:18
Duplicate of #200

**Closed by audn** 2022-05-20 14:18 UTC
Labels: ui
