### ISSUE TITLE
[bug] User-Settings-Modal can not be closed

### ISSUE THREAD

**Issue by SCDerox** [discordlist-gg/beta-issues#230] opened 2022-05-24 14:04 UTC
### Page

Any page -> Open "Settings" from the menu

#### Steps to reproduce
1. Open any page on discordlist
2. Open the menu and click on "Settings"
3. The settings modal appears
4. Try clicking on the "X" 
5. Observe  

#### Video

https://user-images.githubusercontent.com/43812987/170054875-0cabacda-4585-49ef-953e-82a61a27f51a.mp4

### Notify on issue updates

- [X] Yes

### Discord username

SCDerox#4645

**Comment by audn** [comment] 2022-05-24 14:07
Duplicate of #225

**Closed by audn** 2022-05-24 14:07 UTC
Labels: bug

**Comment by SCDerox** [comment] 2022-05-24 14:25
Ups, didn't check the closed issues, my bad, sorry ^^
