### ISSUE TITLE
3-dot dropdown on bot pages borked on safari

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#197] opened 2022-05-18 20:59 UTC
### Description
https://files.circuitsacul.dev/snap_5e4de1a2.png

The menu items extend beyond the side of the dropdown.

### Browser
Safari 15.4

**Comment by audn** [comment] 2022-05-19 18:46
Duplicate of #186

For future references, please attach images instead of just adding external links, thanks!

**Closed by audn** 2022-05-19 18:46 UTC
Labels: bug
