### ISSUE TITLE
Bot Categories seem to show higher numbers than the total number of bots

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#143] opened 2022-05-12 04:26 UTC
### Description
The bot categories seem to show a higher number than the total number of bots, though they show different numbers on each (random maybe?).

### Pictures
<img width="1343" alt="Screen Shot 2022-05-12 at 12 25 17 AM" src="https://user-images.githubusercontent.com/55721663/167991910-a64a5c5d-e189-451b-83af-558fb0545e74.png">
<img width="936" alt="Screen Shot 2022-05-12 at 12 25 48 AM" src="https://user-images.githubusercontent.com/55721663/167991952-c14a1552-8b90-4c0a-ac8d-83447de7010a.png">

### Browser
 - Safari 15.4

**Comment by audn** [comment] 2022-05-13 05:57
Duplicate of #139

**Closed** 2022-05-13 14:02 UTC
Labels: duplicate
