### ISSUE TITLE
[bug]  incorrect render of role icons on page transition

### ISSUE THREAD

**Issue by treboryx** [discordlist-gg/beta-issues#289] opened 2022-06-05 14:49 UTC
### Page

https://discordlist.gg/user/254279600841031680

### Description

Incorrect render of role icons on page transition

technical explanation:
you're probably using the array index as key, but should probably use the role slug to fix this issue

video:

https://user-images.githubusercontent.com/5408097/172056351-9f970ce9-e8b5-45c8-9c68-ee6776804e53.mp4

### Notify on issue updates

- [X] Yes

### Discord username

Robert#0006

**Comment by audn** [comment] 2022-06-05 15:09
Duplicate of #257

**Closed by audn** 2022-06-05 15:09 UTC
Labels: bug
