### ISSUE TITLE
[bug] Data is saved after submitting a bot | bot/new

### ISSUE THREAD

**Issue by GamerCreator1** [discordlist-gg/beta-issues#243] opened 2022-05-27 16:49 UTC
### Page

https://beta.discordlist.gg/bot/new

### Description

Data is saved from the old bot when a bot is submitted, making it show
<img width="434" alt="image" src="https://user-images.githubusercontent.com/58714825/170743551-3e05255d-4880-47ed-94b8-7ba32a98af1f.png">
and also having to remove all the data 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/58714825/170743606-e3971b16-222b-48cf-b304-3940fd45078a.png">

### Notify on issue updates

- [X] Yes

### Discord username

GamerCreator1#1466

**Comment by audn** [comment] 2022-05-27 16:51
Duplicate of #177

**Closed by audn** 2022-05-27 16:51 UTC
Labels: bug
