### ISSUE TITLE
Small grammar issues on Premium page.

### ISSUE THREAD

**Issue by Uhuh** [discordlist-gg/beta-issues#15] opened 2021-08-27 20:09 UTC
## Original text
By upgrading to Pro, `you` listing is likely to get 30% more clicks`.`

## New text
By upgrading to Pro, `your` listing is likely to get 30% more clicks`.`

## Link to the page this typo was found on
https://beta.discordlist.gg/plans
![image](https://user-images.githubusercontent.com/14780600/131183013-c16d7725-5609-4643-b81b-465d82107fb7.png)

**Comment by audn** [comment] 2021-09-01 06:26
Duplicate of #12

**Closed by audn** 2021-09-01 06:26 UTC
Labels: typo, frontend
